FROM debian:bullseye

RUN apt update && apt install -y mariadb-server

RUN mkdir -p /run/mysqld && chown mysql:mysql /run/mysqld

# Demarrer MariaDB
COPY conf/mariadb-conf.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/mariadb-conf.sh

ENTRYPOINT ["/usr/local/bin/mariadb-conf.sh"]
CMD ["mysqld"]
