FROM debian:bullseye

# Installation des dépendances
RUN apt-get update && apt-get install -y \
    php7.4 \
    php7.4-fpm \
    php7.4-mysql \
    php7.4-gd \
    php7.4-mbstring \
    php7.4-xml \
    php7.4-zip \
    php7.4-curl \
    wget \
    unzip \
    curl \
    mariadb-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Configuration de PHP-FPM
COPY conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf

# Création du répertoire pour les fichiers WordPress
RUN mkdir -p /var/www/html

# Téléchargement de WordPress
RUN wget https://wordpress.org/latest.tar.gz -P /tmp && \
    tar -xzf /tmp/latest.tar.gz -C /tmp && \
    cp -a /tmp/wordpress/. /var/www/html/ && \
    rm -rf /tmp/latest.tar.gz /tmp/wordpress

# Téléchargement de WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

# Changement des permissions
RUN chown -R www-data:www-data /var/www/html

# Copie du script d'initialisation
COPY conf/wordpress-conf.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/wordpress-conf.sh

# Exposition du port PHP-FPM
EXPOSE 9000

# Commande de démarrage
CMD ["/usr/local/bin/wordpress-conf.sh"]