FROM debian:bullseye

RUN apt update && apt upgrade -y \
	&& apt install -y  nginx openssl

RUN nginx -v

# Créer le répertoire des certificats SSL
RUN mkdir -p /run/nginx /etc/nginx/ssl

# Générer un certificat auto-signé
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout /etc/nginx/ssl/inception.key \
  -out /etc/nginx/ssl/inception.crt \
  -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=zmogne.42.fr"

# Copier le fichier de configuration NGINX
COPY conf/nginx.conf /etc/nginx/nginx.conf

# Exposer le port 443
EXPOSE 443

# Créer le répertoire des certificats SSL
RUN mkdir -p /etc/nginx/ssl

# Commande pour démarrer NGINX en mode foreground
CMD ["nginx", "-g", "daemon off;"]

